version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeIC_Automaion0913
  gitServerName: ICAccountTest0913
  gitUrl: https://github.com/MeghaRaj69/EdgeIC_Automaion0913
  gitUsername: MeghaRaj69
  gitToken: edge.scaffolding.EdgeIC_Automaion0913.ICAccountTest0913.gitToken
  gitBranch: Test/CustomBranch/Test
